// Shared security helpers: path jail, ID validation, settings schema, SSRF checks.
import crypto from 'node:crypto'
import fs from 'node:fs'
import fsp from 'node:fs/promises'
import net from 'node:net'
import path from 'node:path'
import dns from 'node:dns/promises'
import { safeStorage } from 'electron'
import {
  AgentProfileId,
  AgentTeam,
  CustomAgent,
  DEFAULT_SETTINGS,
  McpServerConfig,
  ModelId,
  PermissionMode,
  Settings,
  UpdateChannel
} from '@shared/types'

/** Session / request ids generated by this app (hex). */
export const ID_RE = /^[a-f0-9]{8,64}$/i

/** Job ids from the terminal panel. */
export const JOB_ID_RE = /^[a-zA-Z0-9_-]{1,64}$/

export function assertId(id: unknown, label = 'id'): string {
  if (typeof id !== 'string' || !ID_RE.test(id)) {
    throw new Error(`Invalid ${label}`)
  }
  return id
}

export function isValidId(id: unknown): id is string {
  return typeof id === 'string' && ID_RE.test(id)
}

export function isValidJobId(id: unknown): boolean {
  return typeof id === 'string' && JOB_ID_RE.test(id)
}

/**
 * Resolve a path under workspace cwd. Rejects absolute escapes, `..`, and
 * symlink targets that leave the workspace (via realpath when the path exists).
 * For not-yet-created write targets, validates the nearest existing ancestor.
 */
export function resolveInWorkspace(cwd: string, p: string): string {
  const root = path.resolve(cwd)
  const candidate = path.isAbsolute(p) ? path.resolve(p) : path.resolve(root, p)

  // Fast string check before realpath (covers most cases + non-existent files).
  if (!(candidate === root || candidate.startsWith(root + path.sep))) {
    throw new Error(`Path escapes workspace: ${p}`)
  }

  // Walk up to an existing ancestor and realpath it so symlinks can't escape.
  let probe = candidate
  while (!fs.existsSync(probe)) {
    const parent = path.dirname(probe)
    if (parent === probe) break
    probe = parent
  }
  try {
    const realProbe = fs.realpathSync(probe)
    const realRoot = fs.realpathSync(root)
    if (!(realProbe === realRoot || realProbe.startsWith(realRoot + path.sep))) {
      throw new Error(`Path escapes workspace (symlink): ${p}`)
    }
    // Rebuild candidate under realRoot when the existing ancestor was realpath'd.
    if (probe !== candidate) {
      const rel = path.relative(probe, candidate)
      const rebuilt = path.resolve(realProbe, rel)
      if (!(rebuilt === realRoot || rebuilt.startsWith(realRoot + path.sep))) {
        throw new Error(`Path escapes workspace: ${p}`)
      }
      return rebuilt
    }
    return realProbe
  } catch (err) {
    if (err instanceof Error && err.message.startsWith('Path escapes')) throw err
    // realpath failed (permissions) — fall back to string-prefix check already done.
    return candidate
  }
}

export async function resolveInWorkspaceAsync(cwd: string, p: string): Promise<string> {
  return resolveInWorkspace(cwd, p)
}

/** Panel-style resolve that returns null instead of throwing. */
export function safeResolve(cwd: string, rel: string): string | null {
  try {
    return resolveInWorkspace(cwd, rel || '.')
  } catch {
    return null
  }
}

/** Only accept an existing directory (used for session cwd). */
export function assertExistingDir(dir: string): string {
  const abs = path.resolve(dir)
  let st: fs.Stats
  try {
    st = fs.statSync(abs)
  } catch {
    throw new Error('Working directory does not exist')
  }
  if (!st.isDirectory()) throw new Error('Working directory is not a directory')
  try {
    return fs.realpathSync(abs)
  } catch {
    return abs
  }
}

// ---------------------------------------------------------------- settings

const MODELS = new Set<ModelId>(['grok-4.3', 'grok-build-0.1'])
const PERMISSION_MODES = new Set<PermissionMode>(['ask', 'auto-edit', 'full-auto', 'plan-only'])
const THEMES = new Set(['dark', 'light', 'system'])
const PROFILES = new Set<AgentProfileId>(['careful', 'balanced', 'yolo'])
const CHANNELS = new Set<UpdateChannel>(['latest', 'beta'])
const MCP_NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$/
const ALLOW_KEY_RE = /^[a-zA-Z0-9_.:/*@+-]{1,200}$/

function sanitizeMcpServer(raw: unknown): McpServerConfig | null {
  if (!raw || typeof raw !== 'object') return null
  const o = raw as Record<string, unknown>
  const name = String(o.name ?? '').trim()
  const command = String(o.command ?? '').trim()
  if (!MCP_NAME_RE.test(name)) return null
  if (!command || command.length > 512) return null
  // Reject shell metacharacters in command path — args are separate.
  if (/[\n\r\0]/.test(command)) return null
  const args = Array.isArray(o.args)
    ? o.args.filter((a): a is string => typeof a === 'string').map((a) => a.slice(0, 1024)).slice(0, 64)
    : []
  const env: Record<string, string> = {}
  if (o.env && typeof o.env === 'object' && !Array.isArray(o.env)) {
    for (const [k, v] of Object.entries(o.env as Record<string, unknown>)) {
      if (!/^[A-Za-z_][A-Za-z0-9_]{0,127}$/.test(k)) continue
      if (typeof v !== 'string') continue
      env[k] = v.slice(0, 8192)
    }
  }
  return {
    name,
    command,
    args,
    env: Object.keys(env).length ? env : undefined,
    enabled: o.enabled !== false,
    source: typeof o.source === 'string' ? o.source.slice(0, 500) : undefined
  }
}

const AGENT_ID_RE = /^[a-zA-Z0-9_-]{1,64}$/
// Matches the skill slug rule in skills.ts (NAME_RE).
const AGENT_SKILL_RE = /^[a-z0-9][a-z0-9-]{0,39}$/

/** Validate one user-defined agent persona; generate an id if missing. */
function sanitizeCustomAgent(raw: unknown): CustomAgent | null {
  if (!raw || typeof raw !== 'object') return null
  const o = raw as Record<string, unknown>
  const name = String(o.name ?? '').trim().slice(0, 60)
  if (!name) return null
  const id =
    typeof o.id === 'string' && AGENT_ID_RE.test(o.id) ? o.id : crypto.randomBytes(8).toString('hex')
  const instructions = String(o.instructions ?? '').slice(0, 8000)
  const skills = Array.isArray(o.skills)
    ? [...new Set(o.skills.filter((s): s is string => typeof s === 'string' && AGENT_SKILL_RE.test(s)))].slice(0, 60)
    : []
  const model: ModelId =
    typeof o.model === 'string' && MODELS.has(o.model as ModelId)
      ? (o.model as ModelId)
      : DEFAULT_SETTINGS.defaultModel
  const permissionMode: PermissionMode =
    typeof o.permissionMode === 'string' && PERMISSION_MODES.has(o.permissionMode as PermissionMode)
      ? (o.permissionMode as PermissionMode)
      : 'ask'
  return { id, name, instructions, skills, model, permissionMode }
}

/** Validate one team: references custom-agent ids, bounded strings, gate roles. */
function sanitizeTeam(raw: unknown): AgentTeam | null {
  if (!raw || typeof raw !== 'object') return null
  const o = raw as Record<string, unknown>
  const name = String(o.name ?? '').trim().slice(0, 60)
  if (!name) return null
  const id =
    typeof o.id === 'string' && AGENT_ID_RE.test(o.id) ? o.id : crypto.randomBytes(8).toString('hex')
  const description = String(o.description ?? '').trim().slice(0, 500)
  const orchestratorId =
    typeof o.orchestratorId === 'string' && AGENT_ID_RE.test(o.orchestratorId) ? o.orchestratorId : ''
  const memberIds = Array.isArray(o.memberIds)
    ? [...new Set(o.memberIds.filter((m): m is string => typeof m === 'string' && AGENT_ID_RE.test(m)))].slice(0, 20)
    : []
  const reviewGates = Array.isArray(o.reviewGates)
    ? [...new Set(o.reviewGates.filter((g): g is string => typeof g === 'string' && g.trim().length > 0).map((g) => g.trim().slice(0, 80)))].slice(0, 10)
    : []
  return { id, name, description, orchestratorId, memberIds, reviewGates }
}

/**
 * Merge a partial settings patch into current settings with runtime validation.
 * Unknown keys are dropped. Invalid values keep the previous setting.
 */
export function applySettingsPatch(current: Settings, patch: unknown): Settings {
  if (!patch || typeof patch !== 'object' || Array.isArray(patch)) return current
  const p = patch as Record<string, unknown>
  const next: Settings = { ...current }

  if (typeof p.defaultModel === 'string' && MODELS.has(p.defaultModel as ModelId)) {
    next.defaultModel = p.defaultModel as ModelId
  }
  if (typeof p.permissionMode === 'string' && PERMISSION_MODES.has(p.permissionMode as PermissionMode)) {
    next.permissionMode = p.permissionMode as PermissionMode
  }
  if (typeof p.theme === 'string' && THEMES.has(p.theme)) {
    next.theme = p.theme as Settings['theme']
  }
  if (typeof p.customInstructions === 'string') {
    next.customInstructions = p.customInstructions.slice(0, 20_000)
  }
  if (typeof p.enableWebSearch === 'boolean') next.enableWebSearch = p.enableWebSearch
  if (typeof p.memoryEnabled === 'boolean') next.memoryEnabled = p.memoryEnabled
  if (typeof p.memoryWriteApproval === 'boolean') next.memoryWriteApproval = p.memoryWriteApproval
  if (typeof p.enableSubagents === 'boolean') next.enableSubagents = p.enableSubagents
  if (typeof p.autoUpdate === 'boolean') next.autoUpdate = p.autoUpdate
  if (typeof p.notifications === 'boolean') next.notifications = p.notifications
  if (typeof p.agentProfile === 'string' && PROFILES.has(p.agentProfile as AgentProfileId)) {
    next.agentProfile = p.agentProfile as AgentProfileId
  }
  if (typeof p.testAfterEdit === 'boolean') next.testAfterEdit = p.testAfterEdit
  if (typeof p.multiModelRouting === 'boolean') next.multiModelRouting = p.multiModelRouting
  if (typeof p.repoMapEnabled === 'boolean') next.repoMapEnabled = p.repoMapEnabled
  if (typeof p.requireWorkspaceTrust === 'boolean') next.requireWorkspaceTrust = p.requireWorkspaceTrust
  if (typeof p.auditLogEnabled === 'boolean') next.auditLogEnabled = p.auditLogEnabled
  if (typeof p.reducedMotion === 'boolean') next.reducedMotion = p.reducedMotion
  if (typeof p.testCommand === 'string') next.testCommand = p.testCommand.slice(0, 500)
  if (typeof p.updateChannel === 'string' && CHANNELS.has(p.updateChannel as UpdateChannel)) {
    next.updateChannel = p.updateChannel as UpdateChannel
  }
  if (Array.isArray(p.trustedWorkspaces)) {
    next.trustedWorkspaces = p.trustedWorkspaces
      .filter((x): x is string => typeof x === 'string' && x.length > 0 && x.length < 1024)
      .slice(0, 200)
  }

  if (Array.isArray(p.globalAllowlist)) {
    next.globalAllowlist = p.globalAllowlist
      .filter((k): k is string => typeof k === 'string' && ALLOW_KEY_RE.test(k))
      .slice(0, 500)
  }

  if (Array.isArray(p.mcpServers)) {
    const servers: McpServerConfig[] = []
    for (const raw of p.mcpServers.slice(0, 50)) {
      const s = sanitizeMcpServer(raw)
      if (s) servers.push(s)
    }
    next.mcpServers = servers
  }

  if (Array.isArray(p.customAgents)) {
    const agents: CustomAgent[] = []
    const seen = new Set<string>()
    for (const raw of p.customAgents.slice(0, 40)) {
      const a = sanitizeCustomAgent(raw)
      if (a && !seen.has(a.id)) {
        seen.add(a.id)
        agents.push(a)
      }
    }
    next.customAgents = agents
  }
  if (Array.isArray(p.teams)) {
    const teams: AgentTeam[] = []
    const seen = new Set<string>()
    for (const raw of p.teams.slice(0, 40)) {
      const t = sanitizeTeam(raw)
      if (t && !seen.has(t.id)) {
        seen.add(t.id)
        teams.push(t)
      }
    }
    next.teams = teams
  }

  return next
}

export function loadSettingsFromDisk(file: string): Settings {
  try {
    const raw = JSON.parse(fs.readFileSync(file, 'utf8')) as unknown
    return applySettingsPatch({ ...DEFAULT_SETTINGS }, raw)
  } catch {
    return { ...DEFAULT_SETTINGS }
  }
}

// ---------------------------------------------------------------- secrets (MCP env)

interface SecretsBlob {
  mcpEnv: Record<string, Record<string, string>>
}

function secretsFile(userData: string): string {
  return path.join(userData, 'secrets.bin')
}

export function readSecretsBlob(userData: string): SecretsBlob {
  try {
    const raw = fs.readFileSync(secretsFile(userData))
    if (!safeStorage.isEncryptionAvailable()) return { mcpEnv: {} }
    const json = safeStorage.decryptString(raw)
    const parsed = JSON.parse(json) as SecretsBlob
    return { mcpEnv: parsed.mcpEnv && typeof parsed.mcpEnv === 'object' ? parsed.mcpEnv : {} }
  } catch {
    return { mcpEnv: {} }
  }
}

export function writeSecretsBlob(userData: string, blob: SecretsBlob): void {
  if (!safeStorage.isEncryptionAvailable()) {
    throw new Error('OS secure storage is unavailable; cannot save secrets')
  }
  const data = safeStorage.encryptString(JSON.stringify(blob))
  fs.mkdirSync(userData, { recursive: true })
  fs.writeFileSync(secretsFile(userData), data, { mode: 0o600 })
}

/** Split MCP servers into public config (no env) + encrypted env map. */
export function splitMcpSecrets(
  servers: McpServerConfig[]
): { publicServers: McpServerConfig[]; envByName: Record<string, Record<string, string>> } {
  const envByName: Record<string, Record<string, string>> = {}
  const publicServers = servers.map((s) => {
    if (s.env && Object.keys(s.env).length) {
      envByName[s.name] = s.env
    }
    const { env: _env, ...rest } = s
    return { ...rest, env: undefined }
  })
  return { publicServers, envByName }
}

export function mergeMcpSecrets(
  publicServers: McpServerConfig[],
  envByName: Record<string, Record<string, string>>
): McpServerConfig[] {
  return publicServers.map((s) => ({
    ...s,
    env: envByName[s.name] && Object.keys(envByName[s.name]).length ? envByName[s.name] : undefined
  }))
}

// ---------------------------------------------------------------- SSRF

const PRIVATE_HOST_RE =
  /^(localhost|metadata\.google\.internal|.*\.local|127\.|0\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|\[?::1\]?$|\[?f[cd])/i

export function isPrivateHostname(hostname: string): boolean {
  const h = hostname.replace(/\.$/, '').toLowerCase()
  if (PRIVATE_HOST_RE.test(h)) return true
  // Decimal / bare IPv4
  if (net.isIP(h) === 4) return isPrivateIp(h)
  if (net.isIP(h) === 6) return isPrivateIp(h)
  return false
}

export function isPrivateIp(ip: string): boolean {
  if (net.isIP(ip) === 4) {
    const parts = ip.split('.').map(Number)
    if (parts.length !== 4 || parts.some((n) => Number.isNaN(n))) return true
    const [a, b] = parts
    if (a === 0 || a === 10 || a === 127) return true
    if (a === 169 && b === 254) return true
    if (a === 192 && b === 168) return true
    if (a === 172 && b >= 16 && b <= 31) return true
    if (a >= 224) return true // multicast / reserved
    return false
  }
  if (net.isIP(ip) === 6) {
    const lower = ip.toLowerCase()
    if (lower === '::1' || lower === '::') return true
    if (lower.startsWith('fc') || lower.startsWith('fd')) return true // ULA
    if (lower.startsWith('fe80')) return true // link-local
    // IPv4-mapped
    const mapped = /^::ffff:(\d+\.\d+\.\d+\.\d+)$/i.exec(lower)
    if (mapped) return isPrivateIp(mapped[1])
    return false
  }
  return true
}

/** Resolve hostname and reject if any address is private. */
export async function assertPublicUrl(url: URL): Promise<void> {
  if (url.protocol !== 'https:' && url.protocol !== 'http:') {
    throw new Error('Only http(s) URLs can be fetched.')
  }
  if (isPrivateHostname(url.hostname)) {
    throw new Error('Refusing to fetch local/private addresses.')
  }
  if (net.isIP(url.hostname)) {
    if (isPrivateIp(url.hostname)) throw new Error('Refusing to fetch local/private addresses.')
    return
  }
  try {
    const results = await dns.lookup(url.hostname, { all: true, verbatim: true })
    if (!results.length) throw new Error('DNS lookup returned no addresses.')
    for (const r of results) {
      if (isPrivateIp(r.address)) {
        throw new Error('Refusing to fetch local/private addresses.')
      }
    }
  } catch (err) {
    if (err instanceof Error && err.message.startsWith('Refusing')) throw err
    throw new Error(`DNS lookup failed: ${err instanceof Error ? err.message : String(err)}`, { cause: err })
  }
}

// ---------------------------------------------------------------- bash allowlist

/** Shell metacharacters that make argv0 allowlisting unsafe. */
const BASH_META_RE = /[;&|`$()<>\n\r]|&&|\|\||>>|<<|\n/

export function bashAllowKey(command: string): string | null {
  const trimmed = command.trim()
  if (!trimmed) return null
  // Refuse to learn/reuse allowlist entries for compound commands.
  if (BASH_META_RE.test(trimmed)) return null
  const first = trimmed.split(/\s+/)[0] ?? ''
  if (!first || first.length > 64) return null
  // Only simple command names / paths without flags in the key.
  if (!/^[a-zA-Z0-9_./+-]+$/.test(first)) return null
  return `bash:${first}`
}

/** Path-scoped allow key for write tools, e.g. write_file:@src/foo.ts */
export function writeAllowKey(toolName: string, absPath: string, cwd: string): string {
  let rel: string
  try {
    rel = path.relative(path.resolve(cwd), path.resolve(absPath)).replace(/\\/g, '/')
  } catch {
    rel = absPath
  }
  if (!rel || rel.startsWith('..')) rel = path.basename(absPath)
  return `${toolName}:@${rel.slice(0, 180)}`
}

export async function pathExists(p: string): Promise<boolean> {
  try {
    await fsp.access(p)
    return true
  } catch {
    return false
  }
}
